- index: 0
  tag: 0
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 1
  tag: 1
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 2
  tag: 2
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 3
  tag: 3
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 4
  tag: 4
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 5
  tag: 5
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 6
  tag: 6
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 7
  tag: 7
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 8
  tag: 8
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 9
  tag: 9
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 10
  tag: 10
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
- index: 11
  tag: 11
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - bwd_overfit_threshold
  - init_kld_threshold
  - phase_change_time
  - reward_range
  - energy_function
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  notes: ''
