- index: 0
  tag: 0_vg_lb
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 1
  tag: 1_vg_lme
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 2
  tag: 2_tb
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 3
  tag: 3_vg_to_tb
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 4
  tag: 4_vg_lme_mle
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 5
  tag: 5_vg_lme_bmle
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 6
  tag: 6_vg_to_tb_mle
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 7
  tag: 7_greedy
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 8
  tag: 8_greedy_pmle
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 9
  tag: 9_greedy_mle
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 10
  tag: 10_greedy_rf
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 11
  tag: 11_greedy_pmle_rf
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 12
  tag: 12_greedy_mle_rf
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 13
  tag: 13_vg_lb_rf
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 14
  tag: 14_vg_lme
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 15
  tag: 15_vg_lb
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 16
  tag: 16_super_combo
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 17
  tag: 7_vg_lb_nobuff
  update_keys:
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 18
  tag: 18_greedy_1k
  update_keys:
  - lr_warmup_time
  - lr_anneal_time
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 19
  tag: 19_greedy_2k
  update_keys:
  - lr_warmup_time
  - lr_anneal_time
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 20
  tag: 20_greedy_4k
  update_keys:
  - lr_warmup_time
  - lr_anneal_time
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 21
  tag: 21_greedy_8k
  update_keys:
  - lr_warmup_time
  - lr_anneal_time
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 22
  tag: 22_greedy_1k_f10
  update_keys:
  - lr_warmup_time
  - lr_anneal_time
  - lr_warmup_ratio
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
- index: 23
  tag: 23_greedy_1k_lowmax
  update_keys:
  - lr_warmup_time
  - lr_anneal_time
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - both_ways
  notes: ''
