- index: 0
  tag: 0_qm9_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  notes: ''
- index: 1
  tag: 1_nic_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - molecule
  - molecule_conditioning
  - buffer_path
  notes: ''
- index: 2
  tag: 2_qm9_smallbatch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  notes: ''
- index: 3
  tag: 3_nic_smallbatch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - molecule
  - molecule_conditioning
  - buffer_path
  notes: ''
- index: 4
  tag: 4_qm9_fast_ema
  update_keys:
  - ema_decay
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  notes: ''
- index: 5
  tag: 5_qm9_1kbatch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  notes: ''
- index: 6
  tag: 6_qm9_longtraj
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - min_traj_length
  - max_traj_length
  notes: ''
- index: 7
  tag: 7_qm9_norm
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  notes: ''
- index: 8
  tag: 8_qm9_deep
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  notes: ''
- index: 9
  tag: 9_qm9_wide
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  notes: ''
- index: 10
  tag: 10_qm9_expl
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - exploratory
  - exploration_factor
  - exploration_wd
  notes: ''
- index: 11
  tag: 11_qm9_nopb
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - learn_pb
  notes: ''
- index: 12
  tag: 12_qm9_highvar
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - t_scale
  notes: ''
- index: 13
  tag: 13_nic_RF
  update_keys:
  - fwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - molecule
  - molecule_conditioning
  - buffer_path
  notes: ''
- index: 14
  tag: 14_nic_greedy
  update_keys:
  - fwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - molecule
  - molecule_conditioning
  - buffer_path
  notes: ''
- index: 15
  tag: 15_nic_TB_highcut
  update_keys:
  - fwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - molecule
  - molecule_conditioning
  - buffer_path
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
