- index: 0
  tag: 0_baseline
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 1
  tag: 1_low_lr
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 2
  tag: 2_small_model
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 3
  tag: 3_small_bwd
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 4
  tag: 4_vars_1_1
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 5
  tag: 5_vars_2_2
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 6
  tag: 6_vars_4_4
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 7
  tag: 7_vars_4_4_big_drift
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 8
  tag: 8_low_t_scale
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 9
  tag: 9_greed
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 10
  tag: 10_greed_low_t_scale
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 11
  tag: 11_cooling
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - temp_annealing_max_steps
  - anneal_temperature
  - energy_min_temperature
  notes: ''
- index: 12
  tag: 12_conditional_cooling
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - anneal_temperature
  - temp_annealing_max_steps
  - temperature_conditioning
  notes: ''
- index: 13
  tag: 19_tb_mle_mle
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 14
  tag: 14_just_big_drift
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
