- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 1
  tag: 1_big_greedy
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 2
  tag: 2_very_big_greedy
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 3
  tag: 3_low_fwd_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 4
  tag: 4_high_fwd_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 5
  tag: 5_low_bwd_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 6
  tag: 6_high_bwd_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 7
  tag: 7_low_prior_frac
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 8
  tag: 8_high_prior_frac
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 9
  tag: 9_mk1
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 10
  tag: 10_high_pb
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 11
  tag: 11_low_t_scale
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
