- index: 0
  tag: 0_baseline
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 1
  tag: 1_expl
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 2
  tag: 2_big_expl
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 3
  tag: 3_high_lr
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 4
  tag: 4_high_clip
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 5
  tag: 5_small_model
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 6
  tag: 6_no_norm
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 7
  tag: 7_high_vf
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 8
  tag: 8_low_vf
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 9
  tag: 9_high_vb
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 10
  tag: 10_low_t_scale
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 11
  tag: 11_high_t_scale
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 12
  tag: 12_high_pb_drift
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 13
  tag: 13_no_pb
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - both_ways
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 14
  tag: 14_no_buff
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 15
  tag: 15_rf
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 16
  tag: 16_greed
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 17
  tag: 17_cooling
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - temp_annealing_max_steps
  - anneal_temperature
  notes: ''
- index: 18
  tag: 18_conditional_cooling
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - anneal_temperature
  - temp_annealing_max_steps
  - temperature_conditioning
  notes: ''
- index: 19
  tag: 19_tb_mle_mle
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 20
  tag: 20_tb__mle
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 21
  tag: 21_tb_bmle
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 22
  tag: 22_tb_wbmle
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  notes: ''
- index: 23
  tag: 23_super_combo
  update_keys:
  - lr_policy
  - lr_back
  - gradient_norm_clip
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - temp_annealing_max_steps
  - anneal_temperature
  notes: ''
