#!/usr/bin/env bash
# umaperf0812 -- overnight local uma A/B. Run from energy_sampling/.
#
#   bash configs/umaperf0812/run_night.sh smoke
#   bash configs/umaperf0812/run_night.sh full
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script by BYTE OFFSET and
# re-reads as it goes, so an edit shifts everything after the cursor and it resumes
# mid-token: the first attempt died with `syntax error near ';;'` and wrote a 0-byte
# config, which then failed as a confusing "config is None" traceback. Stop it, edit,
# restart.
#
# SAFETY, because this runs unattended:
#   * every arm is checkpoint_read_only -- it cannot clobber a checkpoint
#   * gpu_guard runs from train.py's __main__ and refuses to start on a busy card
#   * wait_for_gpu queues behind a sibling agent's run rather than co-tenanting
#   * `timeout` caps each arm so a hang cannot burn the night
#   * arms run SEQUENTIALLY -- two CUDA consumers on 16 GB is the known collision
set -u

VENV="C:/Users/mikem/venvs/csd_mxt_gfn/Scripts/python.exe"
export PYTHONPATH="C:/Users/mikem/Projects/mxt_gfn/mxtaltools;C:/Users/mikem/Projects/mxt_gfn/gfn_diffusion"
LOGDIR="configs/umaperf0812/logs"
mkdir -p "$LOGDIR"

ARM_TIMEOUT=${ARM_TIMEOUT:-5400}
GPU_WAIT_MAX=${GPU_WAIT_MAX:-7200}

gpu_free () {
  "$VENV" -c "
import sys; sys.path.insert(0, '.')
import gpu_guard as g
others = g.training_processes(); mem = g.gpu_memory()
if others:
    print('BUSY: ' + others[0][1][:80]); raise SystemExit(1)
if mem and mem[1] < 6000:
    print('BUSY: only %d MB free' % mem[1]); raise SystemExit(1)
print('clear: %d MB free, util %d%%' % (mem[1], mem[3]))
"
}

wait_for_gpu () {
  local waited=0
  while ! gpu_free; do
    if [ "$waited" -ge "$GPU_WAIT_MAX" ]; then
      echo "gave up waiting for the GPU after $((GPU_WAIT_MAX / 60)) min"
      return 1
    fi
    echo "  ... GPU busy, waiting 120s (waited $((waited / 60)) min)"
    sleep 120
    waited=$((waited + 120))
  done
  return 0
}

run_arm () {
  arm="$1"
  vec="$2"
  echo ""
  echo "=============================================================="
  echo "ARM $arm   MXT_VECTORISED_ATOMICDATA=$vec   $(date '+%H:%M:%S')"
  echo "=============================================================="
  if ! wait_for_gpu; then
    echo "SKIPPING $arm -- GPU never freed up"
    return 1
  fi
  cfg="configs/umaperf0812/$arm.yaml"
  log="$LOGDIR/$arm.log"
  # -u / PYTHONUNBUFFERED: python block-buffers stdout to a file, so without this
  # an arm's log sits empty for many minutes and is indistinguishable from a hang.
  MXT_VECTORISED_ATOMICDATA="$vec" PYTHONUNBUFFERED=1 timeout "$ARM_TIMEOUT" \
      "$VENV" -u train.py --config "$cfg" > "$log" 2>&1
  rc=$?
  echo "$arm exit=$rc  ($(date '+%H:%M:%S'))  log: $log"
  grep -iE "gas reference|batch:|batch growth|gpu util|Reducing batch|protocol: stage|OutOfMemory|Error" \
      "$log" | tail -15 | cut -c1-155
  return $rc
}

mode="${1:-smoke}"
if [ "$mode" = "smoke" ]; then
  run_arm smoke 1
elif [ "$mode" = "full" ]; then
  run_arm a_baseline 0
  run_arm b_optimised 1
  run_arm c_controller 1
  echo ""
  echo "all arms done $(date '+%H:%M:%S') -- analyse with configs/umaperf0812/analyse.py"
else
  echo "usage: $0 [smoke|full]"
  exit 2
fi
