- index: 0
  run_name: uncond_july16_h512_dplr0_T10_clip100.0
  hidden_dim: 512
  dplr_rank: 0
  T: 10
  gradient_norm_clip: 100.0
  max_batch_size: 5000
- index: 1
  run_name: uncond_july16_h512_dplr0_T20_clip100.0
  hidden_dim: 512
  dplr_rank: 0
  T: 20
  gradient_norm_clip: 100.0
  max_batch_size: 5000
- index: 2
  run_name: uncond_july16_h512_dplr5_T10_clip100.0
  hidden_dim: 512
  dplr_rank: 5
  T: 10
  gradient_norm_clip: 100.0
  max_batch_size: 5000
- index: 3
  run_name: uncond_july16_h512_dplr5_T20_clip100.0
  hidden_dim: 512
  dplr_rank: 5
  T: 20
  gradient_norm_clip: 100.0
  max_batch_size: 5000
- index: 4
  run_name: uncond_july16_h512_dplr10_T10_clip100.0
  hidden_dim: 512
  dplr_rank: 10
  T: 10
  gradient_norm_clip: 100.0
  max_batch_size: 5000
- index: 5
  run_name: uncond_july16_h512_dplr10_T20_clip100.0
  hidden_dim: 512
  dplr_rank: 10
  T: 20
  gradient_norm_clip: 100.0
  max_batch_size: 5000
- index: 6
  run_name: uncond_july16_h1024_dplr0_T10_clip100.0
  hidden_dim: 1024
  dplr_rank: 0
  T: 10
  gradient_norm_clip: 100.0
  max_batch_size: 2500
- index: 7
  run_name: uncond_july16_h1024_dplr0_T20_clip100.0
  hidden_dim: 1024
  dplr_rank: 0
  T: 20
  gradient_norm_clip: 100.0
  max_batch_size: 2500
- index: 8
  run_name: uncond_july16_h1024_dplr5_T10_clip100.0
  hidden_dim: 1024
  dplr_rank: 5
  T: 10
  gradient_norm_clip: 100.0
  max_batch_size: 2500
- index: 9
  run_name: uncond_july16_h1024_dplr5_T20_clip100.0
  hidden_dim: 1024
  dplr_rank: 5
  T: 20
  gradient_norm_clip: 100.0
  max_batch_size: 2500
- index: 10
  run_name: uncond_july16_h1024_dplr10_T10_clip100.0
  hidden_dim: 1024
  dplr_rank: 10
  T: 10
  gradient_norm_clip: 100.0
  max_batch_size: 2500
- index: 11
  run_name: uncond_july16_h1024_dplr10_T20_clip100.0
  hidden_dim: 1024
  dplr_rank: 10
  T: 20
  gradient_norm_clip: 100.0
  max_batch_size: 2500
- index: 12
  run_name: uncond_july16_h512_dplr0_T10_clip0.1
  hidden_dim: 512
  dplr_rank: 0
  T: 10
  gradient_norm_clip: 0.1
  max_batch_size: 5000
- index: 13
  run_name: uncond_july16_h512_dplr0_T10_clip10.0
  hidden_dim: 512
  dplr_rank: 0
  T: 10
  gradient_norm_clip: 10.0
  max_batch_size: 5000
- index: 14
  run_name: uncond_july16_h1024_dplr0_T10_clip0.1
  hidden_dim: 1024
  dplr_rank: 0
  T: 10
  gradient_norm_clip: 0.1
  max_batch_size: 2500
- index: 15
  run_name: uncond_july16_h1024_dplr0_T10_clip10.0
  hidden_dim: 1024
  dplr_rank: 0
  T: 10
  gradient_norm_clip: 10.0
  max_batch_size: 2500
