defaults:
  base: base.yaml

experiments:
  - tag: 0_greedy_var_bmle
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 1.0
        mle: 0.0
        smoothed: 0
        var: 10.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0 # exclusive with vg_lb
        mle: 1.0
        smoothed: 0
    notes:

  - tag: 1_tb_var_bmle
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0.0
        mle: 0.0
        smoothed: 0
        var: 10.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0 # exclusive with vg_lb
        mle: 1.0
        smoothed: 0
    notes:

  - tag: 2_greedy_sbmle
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 1.0
        mle: 0.0
        smoothed: 0
        var: 0.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0 # exclusive with vg_lb
        mle: 0.1
        smoothed: 0
    notes:

  - tag: 3_greedy_stb_var_svg
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0.1
        mle: 0.0
        smoothed: 0
        var: 10.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
    notes:

  - tag: 4_greedy_vg_var_vg
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0  # exclusive with vg_lb
        greedy: 1.0
        mle: 0.0
        smoothed: 0
        var: 10.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
    notes:

  - tag: 5_mix
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0.1
        mle: 1.0
        smoothed: 0
        var: 10.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 1.0
        smoothed: 0
    notes:

  - tag: 6_greedy_var_big_mle
    update:
      joint_layers: 8
      hidden_dim: 512
      s_emb_dim: 512
      norm: null
      dropout: 0
      fwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 1.0
        mle: 1.0
        smoothed: 0
        var: 10.0  # penalize forward policy for crowded samples - this and buffer will anneal on expl timescale
        var_gamma: 0.05  # smaller -> longer range repulsion
        var_cutoff: 2.0  # variance below which to penalize
        buffer: 0.0  # penalize forward policy for sampling near samples already in the buffer
        buffer_gamma: 1.0  # smaller -> longer range repulsion
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 0.0 # exclusive with vg_lb
        mle: 1.0
        smoothed: 0
    notes:
