defaults:
  base: base.yaml

experiments:
- tag: 0_baseline
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 1_tb_vg
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 0
      vg_lme: 1
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 2_tb_vg_lme
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 0
      vg_lme: 1
      mle: 1
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 3_hot_tb
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 10

- tag: 4_cold_tb
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 0.1

- tag: 5_cooling
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 10
    energy_min_temperature: 0.01
    energy_max_temperature: 10
    anneal_temperature: True

- tag: 6_conditional_T
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 0
      vg_lme: 1
      emp_z: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 0
      vg_lme: 1
      emp_z: 1
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 10
    energy_min_temperature: 0.01
    energy_max_temperature: 10
    anneal_temperature: True
    temperature_conditioning: True


- tag: 7_high_var_stiff
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 1.0
    log_var_range: 1
    pb_drift_range: 0.2
    pb_var_range: 1
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 8_mid_var_stiff
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 1
    pb_drift_range: 0.2
    pb_var_range: 1
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 9_low_var_stiff
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.01
    log_var_range: 1
    pb_drift_range: 0.2
    pb_var_range: 1
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1


- tag: 10_high_var_flex
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 1.0
    log_var_range: 8
    pb_drift_range: 0.2
    pb_var_range: 8
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 11_mid_var_flex
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 8
    pb_drift_range: 0.2
    pb_var_range: 8
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 12_low_var_flex
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.01
    log_var_range: 8
    pb_drift_range: 0.2
    pb_var_range: 8
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 13_no_pb
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1
    learn_pb: False

- tag: 14_fwd_only
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 0
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1
    both_ways: False
  
- tag: 15_baseline_no_preload
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: null #'/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1
    
- tag: 16_focus_preload
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: [[0, 10], [20000, 10], [30000, 0.01]]
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 17_greedy_late
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: [[0, 0], [10000, 0], [30000, 5]]
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 18_small_dropout
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0.25
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 19_big_dropout
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 8
    hidden_dim: 512
    dropout: 0.5
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1

- tag: 20_deep
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    gradient_norm_clip: 0.1
    max_batch_size: 250
    repeats: 5
    joint_layers: 16
    hidden_dim: 512
    dropout: 0
    norm: layer
    t_scale: 0.1
    log_var_range: 2
    pb_drift_range: 0.2
    pb_var_range: 2
    fwd_loss_coeffs:
      tb: 1
      greedy: 0
      reinforce: 0
      mle: 0
    bwd_loss_coeffs:
      tb: 1
      vg_lme: 0
      mle: 0
      mle_prior_fraction: 0
      pmle_std: 0
    buffer_path: '/scratch/mk8347/csd_runs/datasets/qm9_sg2_dataset.pt'
    exploratory: False
    exploration_factor: 0.25
    exploration_wd: True
    wd_max_steps: 10000
    energy_static_temperature: 1