defaults:
  base: base.yaml


experiments:
- tag: 0_baseline
  update:
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null

- tag: 1_wide
  update:
    joint_layers: 4
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.0
    norm: null

- tag: 2_deep
  update:
    joint_layers: 8
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null

- tag: 3_skinnydeep
  update:
    joint_layers: 16
    hidden_dim: 256
    s_emb_dim: 256
    condition_emb_dim: 256
    t_emb_dim: 256
    dropout: 0.0
    norm: null

- tag: 4_norm
  update:
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: layer

- tag: 5_bignorm
  update:
    joint_layers: 8
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.5
    norm: null

- tag: 6_baseline_highlr
  update:
    lr_policy: 0.001
    lr_back: 0.001
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null


- tag: 7_baseline_smallbatch
  update:
    lr_policy: 0.001
    lr_back: 0.001
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null
    max_batch_size: 2000


- tag: 8_baseline_bigbatch
  update:
    lr_policy: 0.001
    lr_back: 0.001
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null
    max_batch_size: 10000

- tag: 9_new_allin
  update:
    lr_policy: 0.001
    lr_back: 0.001
    joint_layers: 8
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.0
    norm: layer
    max_batch_size: 5000

- tag: 10_new_superwide
  update:
    lr_policy: 0.001
    lr_back: 0.001
    joint_layers: 8
    hidden_dim: 2048
    s_emb_dim: 2048
    condition_emb_dim: 2048
    t_emb_dim: 2048
    dropout: 0.0
    norm: layer
    max_batch_size: 5000

- tag: 11_new_nonorm
  update:
    lr_policy: 0.001
    lr_back: 0.001
    joint_layers: 8
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.0
    norm: null
    max_batch_size: 5000

- tag: 12_new_superbig_lowlr
  update:
    lr_policy: 0.0001
    lr_back: 0.0001
    joint_layers: 16
    hidden_dim: 2048
    s_emb_dim: 2048
    condition_emb_dim: 2048
    t_emb_dim: 2048
    dropout: 0.0
    norm: layer
    max_batch_size: 5000

- tag: 13_new_allin
  update:
    lr_policy: 0.00005
    lr_back: 0.00005
    joint_layers: 8
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.0
    norm: layer
    max_batch_size: 5000

- tag: 14_new_superwide
  update:
    lr_policy: 0.00005
    lr_back: 0.00005
    joint_layers: 8
    hidden_dim: 2048
    s_emb_dim: 2048
    condition_emb_dim: 2048
    t_emb_dim: 2048
    dropout: 0.0
    norm: layer
    max_batch_size: 5000

- tag: 15_new_nonorm
  update:
    lr_policy: 0.00005
    lr_back: 0.00005
    joint_layers: 8
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.0
    norm: null
    max_batch_size: 5000

- tag: 16_new_superbig_lowlr
  update:
    lr_policy: 0.00001
    lr_back: 0.00001
    joint_layers: 16
    hidden_dim: 2048
    s_emb_dim: 2048
    condition_emb_dim: 2048
    t_emb_dim: 2048
    dropout: 0.0
    norm: layer
    max_batch_size: 5000