defaults:
  base: base.yaml


experiments:
- tag: 0_baseline
  update:
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null

- tag: 1_wide
  update:
    joint_layers: 4
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.0
    norm: null

- tag: 2_deep
  update:
    joint_layers: 8
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: null

- tag: 3_skinnydeep
  update:
    joint_layers: 16
    hidden_dim: 256
    s_emb_dim: 256
    condition_emb_dim: 256
    t_emb_dim: 256
    dropout: 0.0
    norm: null

- tag: 4_norm
  update:
    joint_layers: 4
    hidden_dim: 512
    s_emb_dim: 512
    condition_emb_dim: 512
    t_emb_dim: 512
    dropout: 0.0
    norm: layer

- tag: 5_bignorm
  update:
    joint_layers: 8
    hidden_dim: 1024
    s_emb_dim: 1024
    condition_emb_dim: 1024
    t_emb_dim: 1024
    dropout: 0.5
    norm: null
