T: 10
anneal_energy: false
annealing_max_steps: 5000
batch_size: 25
beta: 0.1
both_ways: false
buffer_path: null
buffer_size: 50000
burn_in: 100
bwd: false
bwd_batch_multiplier: 5
bwd_policy: brownian_bridge
clipping: true
condition_emb_dim: 12
conditional_flow_model: false
convergence_history: 100
device: cuda
discretizer: random
discretizer_max_ratio: 10
dropout: 0
energy: molecular_crystal
energy_annealing_threshold: 0.1
energy_clip: 100
energy_density_coeff: 2.0
energy_function: ellipsoid_overlap
energy_max_temperature: 1
energy_min_temperature: 0.01
energy_static_temperature: 1
epochs: 1000000
eval: false
eval_T: 100
eval_batch_size: 500
eval_period: 500
exploration_factor: 1
exploration_wd: true
exploratory: true
figs_period: 500
fwd_train_each: 2
gfn_clip: 10.0
gradient_norm_clip: 1.0
grow_batch_size: true
harmonics_dim: 64
hidden_dim: 256
joint_layers: 4
langevin: false
langevin_scaling_per_dimension: false
ld_schedule: true
ld_step: 0.1
learn_pb: false
learned_variance: false
lgv_clip: 100.0
lgv_layers: 4
local_search: false
log_var_range: 4.0
lr_anneal_time: 20000
lr_back: 0.001
lr_flow: 0.1
lr_policy: 0.001
lr_warmup_time: 500
ls_cycle: 100
max_batch_size: 2000
max_iter_ls: 100
max_traj_length: 15
min_lr: 1.0e-06
min_traj_length: 10
mode_bwd: combo
mode_fwd: combo
molecules_path: /scratch/mk8347/csd_runs/datasets/test_qm9_dataset.pt
norm: null
partial_energy: false
pb_scale_range: 0.1
pis_architectures: false
prioritized: boltzmann
rank_weight: 1.0
repeats: 5
run_name: urea_7
s_emb_dim: 256
samples_per_opt: 10
sampling: buffer
scheduler: true
seed: 12345
subtb_lambda: 2
t_emb_dim: 32
t_scale: 0.5
target_acceptance_rate: 0.574
temperature_conditioning: false
temperature_scaling_factor: 0.01
traj_length_strategy: sampled
use_weight_decay: false
wd_max_steps: 10000
weight_decay: 1e-7
zero_init: true
