- index: 0
  tag: 0
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 1
  tag: 1
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 2
  tag: 2
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 3
  tag: 3
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 4
  tag: 4
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 5
  tag: 5
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 6
  tag: 6
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 7
  tag: 7
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 8
  tag: 8
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 9
  tag: 9
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 10
  tag: 10
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 11
  tag: 11
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  notes: ''
- index: 12
  tag: 12
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  - learn_pb
  notes: ''
- index: 13
  tag: 13
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  - learn_pb
  - learned_variance
  notes: ''
- index: 14
  tag: 12
  update_keys:
  - T
  - eval_T
  - energy_clip
  - energy_static_temperature
  - learn_pb
  - pb_var_range
  notes: ''
