defaults:
  base: base.yaml


# check variance, pb, temperature, energy clip, batch size, lr
experiments:
- tag: 0
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: true
    learned_variance: true

- tag: 1 # slightly slower to train, perhaps
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 1000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: true
    learned_variance: true

- tag: 2  # failed MLE task
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: true
    learned_variance: false

- tag: 3  # variance explosion
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: false
    learned_variance: true

- tag: 4  # slightly worse training
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 4
    learn_pb: true
    learned_variance: true

- tag: 5 # tighter convergence, much larger distribution shift. Led into variance explosion failure mode
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.5
    pb_var_range: 2
    learn_pb: true
    learned_variance: true

- tag: 6  #tighter convergence, larger distribution shift, worse energies but no explosion
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 6
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: true
    learned_variance: true

- tag: 7  # rather good, starting to concentrate at lower and lower energies. no explosions. Weak backward anchor. Ema model would probably be nice
  update:
    T: 50
    eval_T: 50
    energy_clip: 10
    energy_static_temperature: 0.1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: true
    learned_variance: true

- tag: 8  # very different behavior actually. seems like lower effective temperature
  update:
    T: 50
    eval_T: 50
    energy_clip: 100
    energy_static_temperature: 1.0
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    learn_pb: true
    learned_variance: true
