- index: 0
  tag: 0
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  notes: ''
- index: 1
  tag: 1
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  notes: ''
- index: 2
  tag: 2
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  notes: ''
- index: 3
  tag: 3
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  - thermalization_conv_eps
  notes: ''
- index: 4
  tag: 4
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  - thermalization_conv_eps
  notes: ''
- index: 5
  tag: 5
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  - thermalization_conv_eps
  notes: ''
- index: 6
  tag: 6
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  - thermalization_conv_eps
  notes: ''
- index: 7
  tag: 7
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  - thermalization_conv_eps
  notes: ''
- index: 8
  tag: 8
  update_keys:
  - energy_static_temperature
  - max_batch_size
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - energy_function
  - thermalization_conv_eps
  notes: ''
