defaults:
  base: base.yaml


experiments:
- tag: 0
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    init_kld_threshold: 0.05
    btb_threshold: 1.0
    reward_range: 20

- tag: 1
  update:
    energy_static_temperature: 10.0
    thermalization_conv_eps: 0.5
    init_kld_threshold: 0.05
    btb_threshold: 1.0
    reward_range: 20

- tag: 2
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.75
    init_kld_threshold: 0.05
    btb_threshold: 1.0
    reward_range: 20

- tag: 3
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    init_kld_threshold: 0.05
    btb_threshold: 1.0
    reward_range: 10

- tag: 4
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    init_kld_threshold: 0.05
    btb_threshold: 1.0
    reward_range: 40