- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 1
  tag: 1_plus_RF
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 2
  tag: 2_sub_RF
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 3
  tag: 3_with_back_TB
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 4
  tag: 4_.5PMLE
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
