defaults:
  base: base.yaml
#
#Run 3 results
#
#0 - baseline - pretty good
#1 - busted
#2 - t_scale 0.05. Best convergence, log Z
#3 - baseline
#4 - t_scale 0.2. Exploded
#5 - baseline
#6 - log var range 6 - almost identical
#7 - baseline
#8 - pb var range 4 - slower to converge. possibly worse overall hard to say. worse samples
#9 - 50k noise buffer - minimal difference
#10 - baseline
#11 - 0.95 noise fraction - slower convergence but like, sameish overall? Slightly worse?
#12 - baseline
#13 - btb threshold 1.5 - bwd is better. Overall very similar though
#14 - baseline
#15 - baseline
#16 - thermalization conv eps 0.75 - higher bwd loss, slightly worse conv overall

experiments:
- tag: 0
  update:
