- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 1
  tag: 1_fewer-layers
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 2
  tag: 2_more-layers
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 3
  tag: 3_with-dropout
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 4
  tag: 4_with-norm
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 5
  tag: 5_tscale-small
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 6
  tag: 6_pbscale-wide
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 7
  tag: 7_mle-high
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 8
  tag: 8_pmle-high
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 9
  tag: 9_pmle-low
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 10
  tag: 10_small_bmle
  update_keys:
  - joint_layers
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - e2_time
  - e3_time
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
