- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 1
  tag: 1_deep
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 2
  tag: 2_wide
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 3
  tag: 3_big_clip
  update_keys:
  - gradient_norm_clip
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 4
  tag: 4_short_expl
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 5
  tag: 5_long_expl
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 6
  tag: 6_anneal_T
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 7
  tag: 7_anneal_repulsion
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 8
  tag: 8_w_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 9
  tag: 9_low_beta
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 10
  tag: 10_pure_tb
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 11
  tag: 11_tb_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
