- index: 0
  tag: 0_512x8_random_tbtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 1
  tag: 1_512x8_random_tbtb_Pb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 2
  tag: 2_512x8_random_tbtbmle_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 3
  tag: 3_1024x8_random_tbtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 4
  tag: 4_512x16_random_tbtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 5
  tag: 5_512x8_random_tbgtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 6
  tag: 6_512x8_random_tbtbBmle_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 7
  tag: 7_512x8_lowd_tbtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - discretizer
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 8
  tag: 8_512x8_uni_tbtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - discretizer
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 9
  tag: 9_1024x16_random_tbtb_noPb
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
