- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 1
  tag: 1_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 2
  tag: 2_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 3
  tag: 3_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 4
  tag: 4_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 5
  tag: 5_1024_dropout
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 6
  tag: 6_1024_norm
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 7
  tag: 7_1024_norm_dropout
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 8
  tag: 8_1024_deep
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 9
  tag: 9_1024_TB
  update_keys:
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 10
  tag: 10_1024_TB_MLE
  update_keys:
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 11
  tag: 11_1024_TB_VG_MLE
  update_keys:
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
- index: 12
  tag: 12_1024_TB_TB_MLE
  update_keys:
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - norm
  notes: ''
