- index: 0
  tag: 0_ftb_noPb_var_med_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 1
  tag: 1_ftb_noPb_var_nonorm_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 2
  tag: 2_ftb_noPb_var_deep_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 3
  tag: 3_ftb_noPb_var_shallow_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 4
  tag: 4_ftb_noPb_novar_med_zero_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 5
  tag: 5_ftb_noPb_var_dropout_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 6
  tag: 6_ftb_noPb_var_med_high_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 7
  tag: 7_ftb_noPb_var_med_low_low
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 8
  tag: 8_ftb_noPb_var_med_low_high
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 9
  tag: 9_ftb_Pb_var_med_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 10
  tag: 10_ftb_noPb_novar_med_zero_low
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 11
  tag: 11_tb_noPb_var_med_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 12
  tag: 12_tb_Pb_var_med_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 13
  tag: 13_ftbg_noPb_var_med_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 14
  tag: 14_ftbg_noPb_var_med_med_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 15
  tag: 15_ftbg_noPb_novar_med_zero_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 16
  tag: 16_tbg_noPb_var_med_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
- index: 17
  tag: 17_ftbg_noPb_var_dropout_low_med
  update_keys:
  - lr_policy
  - lr_back
  - max_batch_size
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_var_range
  - pb_drift_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - buffer_path
  - both_ways
  - learn_pb
  - learned_variance
  - exploratory
  - exploration_factor
  - exploration_wd
  - wd_max_steps
  - energy_static_temperature
  notes: ''
