- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 1
  tag: 1_deep
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 2
  tag: 2_wide
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 3
  tag: 3_small_var
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - t_scale
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 4
  tag: 4_large_var
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - t_scale
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 5
  tag: 5_small_var_range
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - log_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 6
  tag: 6_large_var_range
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - log_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 7
  tag: 7_large_pb_scale
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 8
  tag: 8_extra_eval_T
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - eval_T
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
- index: 9
  tag: 9_noisy_deep
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - dropout
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - beta
  - exploration_factor
  - wd_max_steps
  - anneal_temperature
  - anneal_repulsion
  - lj_repulsion
  - ellipsoid_scale
  - energy_min_temperature
  - energy_max_temperature
  - energy_static_temperature
  - temp_annealing_max_steps
  - repulsion_annealing_max_steps
  notes: null
