defaults:
  base: base.yaml

# to-do
# big model
# short expl
# long expl
# temp annealing
# silu annealing
# mle


experiments:
  - tag: 0_baseline
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 1_deep
    update:
      joint_layers: 8
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 2_wide
    update:
      joint_layers: 4
      hidden_dim: 512
      s_emb_dim: 512
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 3_big_clip
    update:
      gradient_norm_clip: 1.0
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 4_short_expl
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 2500
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 5_long_expl
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 10000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 6_anneal_T
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: true
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 7_anneal_repulsion
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: true
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 8_w_mle
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.1
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.1
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 9_low_beta
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 0.1
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 10_pure_tb
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.0
        smoothed: 0
      bwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0 # exclusive with vg_lb
        mle: 0.0
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes:

  - tag: 11_tb_mle
    update:
      joint_layers: 4
      hidden_dim: 256
      s_emb_dim: 256
      fwd_loss_coeffs:
        tb: 1.0
        vg_lb: 0.0
        vg_lme: 0.0  # exclusive with vg_lb
        greedy: 0
        mle: 0.1
        smoothed: 0
      bwd_loss_coeffs:
        tb: 0.0
        vg_lb: 0.0
        vg_lme: 1.0 # exclusive with vg_lb
        mle: 0.1
        smoothed: 0
      beta: 1.0
      exploration_factor: 1.0
      wd_max_steps: 5000
      anneal_temperature: false
      anneal_repulsion: false
      lj_repulsion: 0.85
      ellipsoid_scale: -0.5
      energy_min_temperature: 0.01
      energy_max_temperature: 10
      energy_static_temperature: 1
      temp_annealing_max_steps: 10000
      repulsion_annealing_max_steps: 10000
    notes: