- combo:
    log_var_range: 0.5
    t_scale: 0.1
  index: 0
  notes: ''
  tag: 0_t_scale-0.1_log_var_range-0.5
- combo:
    log_var_range: 1.0
    t_scale: 0.1
  index: 1
  notes: ''
  tag: 1_t_scale-0.1_log_var_range-1.0
- combo:
    log_var_range: 2.0
    t_scale: 0.1
  index: 2
  notes: ''
  tag: 2_t_scale-0.1_log_var_range-2.0
- combo:
    log_var_range: 4.0
    t_scale: 0.1
  index: 3
  notes: ''
  tag: 3_t_scale-0.1_log_var_range-4.0
- combo:
    log_var_range: 8.0
    t_scale: 0.1
  index: 4
  notes: ''
  tag: 4_t_scale-0.1_log_var_range-8.0
- combo:
    log_var_range: 0.5
    t_scale: 0.25
  index: 5
  notes: ''
  tag: 5_t_scale-0.25_log_var_range-0.5
- combo:
    log_var_range: 1.0
    t_scale: 0.25
  index: 6
  notes: ''
  tag: 6_t_scale-0.25_log_var_range-1.0
- combo:
    log_var_range: 2.0
    t_scale: 0.25
  index: 7
  notes: ''
  tag: 7_t_scale-0.25_log_var_range-2.0
- combo:
    log_var_range: 4.0
    t_scale: 0.25
  index: 8
  notes: ''
  tag: 8_t_scale-0.25_log_var_range-4.0
- combo:
    log_var_range: 8.0
    t_scale: 0.25
  index: 9
  notes: ''
  tag: 9_t_scale-0.25_log_var_range-8.0
- combo:
    log_var_range: 0.5
    t_scale: 0.5
  index: 10
  notes: ''
  tag: 10_t_scale-0.5_log_var_range-0.5
- combo:
    log_var_range: 1.0
    t_scale: 0.5
  index: 11
  notes: ''
  tag: 11_t_scale-0.5_log_var_range-1.0
- combo:
    log_var_range: 2.0
    t_scale: 0.5
  index: 12
  notes: ''
  tag: 12_t_scale-0.5_log_var_range-2.0
- combo:
    log_var_range: 4.0
    t_scale: 0.5
  index: 13
  notes: ''
  tag: 13_t_scale-0.5_log_var_range-4.0
- combo:
    log_var_range: 8.0
    t_scale: 0.5
  index: 14
  notes: ''
  tag: 14_t_scale-0.5_log_var_range-8.0
- combo:
    log_var_range: 0.5
    t_scale: 0.75
  index: 15
  notes: ''
  tag: 15_t_scale-0.75_log_var_range-0.5
- combo:
    log_var_range: 1.0
    t_scale: 0.75
  index: 16
  notes: ''
  tag: 16_t_scale-0.75_log_var_range-1.0
- combo:
    log_var_range: 2.0
    t_scale: 0.75
  index: 17
  notes: ''
  tag: 17_t_scale-0.75_log_var_range-2.0
- combo:
    log_var_range: 4.0
    t_scale: 0.75
  index: 18
  notes: ''
  tag: 18_t_scale-0.75_log_var_range-4.0
- combo:
    log_var_range: 8.0
    t_scale: 0.75
  index: 19
  notes: ''
  tag: 19_t_scale-0.75_log_var_range-8.0
- combo:
    log_var_range: 0.5
    t_scale: 1
  index: 20
  notes: ''
  tag: 20_t_scale-1_log_var_range-0.5
- combo:
    log_var_range: 1.0
    t_scale: 1
  index: 21
  notes: ''
  tag: 21_t_scale-1_log_var_range-1.0
- combo:
    log_var_range: 2.0
    t_scale: 1
  index: 22
  notes: ''
  tag: 22_t_scale-1_log_var_range-2.0
- combo:
    log_var_range: 4.0
    t_scale: 1
  index: 23
  notes: ''
  tag: 23_t_scale-1_log_var_range-4.0
- combo:
    log_var_range: 8.0
    t_scale: 1
  index: 24
  notes: ''
  tag: 24_t_scale-1_log_var_range-8.0
