- index: 0
  tag: 0
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 1
  tag: 1
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 2
  tag: 2
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 3
  tag: 3
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 4
  tag: 4
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 5
  tag: 5
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 6
  tag: 6
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 7
  tag: 7
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - btb_threshold
  - reward_range
  notes: ''
- index: 8
  tag: 8
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - eval_period
  - bwd_thermalization_time
  - energy_density_coeff
  - btb_threshold
  - reward_range
  notes: ''
- index: 9
  tag: 9
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - eval_period
  - bwd_thermalization_time
  - energy_density_coeff
  - btb_threshold
  - reward_range
  notes: ''
- index: 10
  tag: 10
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - eval_period
  - bwd_thermalization_time
  - energy_density_coeff
  - btb_threshold
  - reward_range
  notes: ''
- index: 11
  tag: 11
  update_keys:
  - energy_static_temperature
  - thermalization_conv_eps
  - eval_period
  - bwd_thermalization_time
  - energy_density_coeff
  - btb_threshold
  - reward_range
  notes: ''
- index: 12
  tag: 1_restart
  update_keys:
  - eval_period
  - energy_static_temperature
  - thermalization_conv_eps
  - checkpoint_path
  - buffer_size
  - starting_phase
  - btb_threshold
  - reward_range
  - bwd_thermalization_time
  - max_fwd_batch_size
  - max_bwd_batch_size
  notes: ''
- index: 13
  tag: 4_restart
  update_keys:
  - eval_period
  - energy_static_temperature
  - thermalization_conv_eps
  - checkpoint_path
  - buffer_size
  - btb_threshold
  - reward_range
  - starting_phase
  - bwd_thermalization_time
  - max_fwd_batch_size
  - max_bwd_batch_size
  notes: ''
