defaults:
  base: base.yaml


experiments:
- tag: 0
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    
    btb_threshold: 1.0
    reward_range: 20

- tag: 1
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    
    btb_threshold: 1.0
    reward_range: 40

- tag: 2
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.25
    
    btb_threshold: 1.0
    reward_range: 20

- tag: 3
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.25
    
    btb_threshold: 1.0
    reward_range: 40

- tag: 4
  update:
    energy_static_temperature: 10
    thermalization_conv_eps: 0.5
    
    btb_threshold: 1.0
    reward_range: 20

- tag: 5
  update:
    energy_static_temperature: 10
    thermalization_conv_eps: 0.5
    
    btb_threshold: 1.0
    reward_range: 40

- tag: 6
  update:
    energy_static_temperature: 10
    thermalization_conv_eps: 0.25
    
    btb_threshold: 1.0
    reward_range: 20

- tag: 7
  update:
    energy_static_temperature: 10
    thermalization_conv_eps: 0.25
    
    btb_threshold: 1.0
    reward_range: 40

- tag: 8
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    eval_period: 500
    bwd_thermalization_time: 1000
    energy_density_coeff: 100.0
    btb_threshold: 1.5
    reward_range: 20

- tag: 9
  update:
    energy_static_temperature: 2.5
    thermalization_conv_eps: 0.5
    eval_period: 500
    bwd_thermalization_time: 1000
    energy_density_coeff: 100.0
    btb_threshold: 1.5
    reward_range: 100

- tag: 10
  update:
    energy_static_temperature: 10.0
    thermalization_conv_eps: 0.5
    eval_period: 500
    bwd_thermalization_time: 1000
    energy_density_coeff: 100.0
    btb_threshold: 1.5
    reward_range: 20

- tag: 11
  update:
    energy_static_temperature: 10.0
    thermalization_conv_eps: 0.5
    eval_period: 500
    bwd_thermalization_time: 1000
    energy_density_coeff: 100.0
    btb_threshold: 1.5
    reward_range: 100
