- index: 0
  tag: 0_vg_only
  update_keys:
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 1
  tag: 1_vg_and_mle
  update_keys:
  - joint_layers
  - max_batch_size
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 2
  tag: 2_vg_bmle
  update_keys:
  - joint_layers
  - max_batch_size
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 3
  tag: 4_gently_greedy
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 4
  tag: 5_gently_greedy2
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 5
  tag: 5_gently_greedy3_all_noise
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 6
  tag: 6_greedy_RF
  update_keys:
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 7
  tag: 7_greedy_RF_big_mle
  update_keys:
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 8
  tag: 8_vg_only_tight_pb
  update_keys:
  - max_batch_size
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - log_var_range
  - pb_drift_range
  - pb_var_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
