# Shared across all runs
base:
  device: cuda
  n_steps: 100
  zp: 1
  kT: 2.5
  units: 'kJ/mol'

  num_samples: 10000
  batch_size: 10
  alpha: 2.0

  reload_results: false
  save_results: true
  overwrite_results: true

  data_root: D:\crystal_datasets
  results_dir: D:\crystal_datasets\gfn_results

# Per-run overrides
runs:
  - run_name: acridine_14_1
    energy_function: mace
    sg_ind: 14
    z_prime: 1
    model_path: D:\crystal_datasets\acridine\models\run_1_acridine_14_1_model_eval.pt
    config_path: D:\crystal_datasets\acridine\models\run_1_acridine_14_1_model_config.npy
    molecule_path: D:\crystal_datasets\acridine\acridine_conformer.pt
    exp_sample_path: D:\crystal_datasets\acridine\opt_acrdin.pt #std_acridine_polymorphs.pt
    dataset_path: D:\crystal_datasets\acridine\may_acridine_sg14_zp1_prior_dataset.pt
    identifiers: ['ACRDIN04','ACRDIN12']

  - run_name: mipcas_elj
    energy_function: elj
    sg_ind: 2
    z_prime: 1
    model_path:    D:\crystal_datasets\mipcas\new_mipcas_2_mipcas_2_baseline_0_model_eval.pt
    config_path:   D:\crystal_datasets\mipcas\new_mipcas_2_mipcas_2_baseline_0_model_config.npy
    molecule_path: D:\crystal_datasets\mipcas\MIPCAS_standardized.pt
    exp_sample_path: D:\crystal_datasets\mipcas\MIPCAS_standardized.pt
    dataset_path:  D:\crystal_datasets\mipcas\mipcas_elj_prior_dataset.pt

  - run_name: mipcas_uma
    energy_function: uma
    sg_ind: 2
    z_prime: 1
    model_path:    D:\crystal_datasets\mipcas\new_mipcas_2_mipcas_2_uma_baseline_10_model_eval.pt
    config_path:   D:\crystal_datasets\mipcas\new_mipcas_2_mipcas_2_uma_baseline_10_model_config.npy
    molecule_path: D:\crystal_datasets\mipcas\MIPCAS_standardized.pt
    exp_sample_path: D:\crystal_datasets\mipcas\MIPCAS_standardized.pt
    dataset_path:  D:\crystal_datasets\mipcas\mipcas_uma_prior_dataset.pt

  - run_name: nehzor_elj
    energy_function: elj
    sg_ind: 14
    z_prime: 1
    model_path:    D:\crystal_datasets\nehzor\new_nehzor_2_nehzor_2_elj_1_model_eval.pt
    config_path:   D:\crystal_datasets\nehzor\new_nehzor_2_nehzor_2_elj_1_model_config.npy
    molecule_path: D:\crystal_datasets\nehzor\NEHZOR_structures_std_conf.pt
    exp_sample_path: D:\crystal_datasets\nehzor\NEHZOR_structures_std_conf.pt
    dataset_path:  D:\crystal_datasets\nehzor\nehzor_elj_prior_dataset.pt

  - run_name: nehzor_uma
    energy_function: uma
    sg_ind: 14
    z_prime: 1
    model_path:    D:\crystal_datasets\nehzor\new_nehzor_2_nehzor_2_uma_0_model_eval.pt
    config_path:   D:\crystal_datasets\nehzor\new_nehzor_2_nehzor_2_uma_0_model_config.npy
    molecule_path: D:\crystal_datasets\nehzor\NEHZOR_structures_std_conf.pt
    exp_sample_path: D:\crystal_datasets\nehzor\NEHZOR_structures_std_conf.pt
    dataset_path:  D:\crystal_datasets\nehzor\nehzor_uma_prior_dataset.pt