- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 1
  tag: 1_1k_batch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 2
  tag: 2_4k_batch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 3
  tag: 3_8k_batch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 4
  tag: 4_6_layers
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 5
  tag: 5_2_layers
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 6
  tag: 6_8_layers
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 7
  tag: 7_1024_dim
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 8
  tag: 8_no_norm
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
- index: 9
  tag: 9_.5_dropout
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - max_batch_size
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - learn_pb
  - learned_variance
  - beta
  - buffer_diversity_coeff
  - anneal_repulsion_cutoff
  notes: ''
