T: 10
anneal_energy: true
batch_size: 25
beta: 1.0
both_ways: false
buffer_size: 600000
burn_in: 100
bwd: false
clipping: true
conditional_flow_model: false
dataset_path: D:/crystal_datasets/urea_gfn_dataset.pt
device: cuda
dropout: 0
energy: molecular_crystal
energy_temperature: 1.0
epochs: 10000000
eval: false
eval_period: 100
exploration_factor: 0.35
exploration_wd: true
exploratory: true
gfn_clip: 10000.0
gradient_norm_clip: 10.0
grow_batch_size: true
harmonics_dim: 64
hidden_dim: 256
joint_layers: 4
langevin: false
langevin_scaling_per_dimension: false
ld_schedule: true
ld_step: 0.1
learn_pb: false
learned_variance: true
lgv_clip: 100.0
lgv_layers: 4
local_search: false
log_var_range: 4.0
lr_back: 0.0001
lr_flow: 0.01
lr_policy: 0.0001
ls_cycle: 100
max_batch_size: 500
max_iter_ls: 100
mode_bwd: tb
mode_fwd: tb
norm: null
partial_energy: false
pb_scale_range: 0.1
pis_architectures: false
prioritized: rank
rank_weight: 0.01
run_name: dev_test_1_2
s_emb_dim: 32
samples_per_opt: 10
sampling: buffer
seed: 12345
subtb_lambda: 2
t_emb_dim: 32
t_scale: 1.0
target_acceptance_rate: 0.574
use_weight_decay: false
weight_decay: 1.0e-07
zero_init: false
