- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  notes: ''
- index: 1
  tag: 1_flexible
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - log_var_range
  - pb_var_range
  notes: ''
- index: 2
  tag: 2_wide
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  notes: ''
- index: 3
  tag: 3_norm
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - t_emb_dim
  - dropout
  - norm
  - log_var_range
  - pb_var_range
  notes: ''
