T: 10
anneal_energy: true
batch_size: 25
beta: 1.0
both_ways: false
buffer_path: D:/crystal_datasets/urea_gfn_dataset.pt
buffer_size: 100000
burn_in: 100
bwd: false
bwd_batch_multiplier: 5
clipping: true
condition_emb_dim: 32
conditional_flow_model: true
convergence_history: 100
device: cuda
dropout: 0.1
energy: molecular_crystal
energy_annealing_threshold: 0.01
energy_density_coeff: 5
energy_max_temperature: 10
energy_min_temperature: 0.01
energy_static_temperature: 1
epochs: 10000000
eval: false
eval_batch_size: 2000
eval_period: 250
exploration_factor: 0.35
exploration_wd: true
exploratory: true
figs_period: 500
fwd_train_each: 1
gfn_clip: 10.0
gradient_norm_clip: 10.0
grow_batch_size: true
harmonics_dim: 32
hidden_dim: 256
joint_layers: 4
langevin: false
langevin_scaling_per_dimension: false
ld_schedule: true
ld_step: 0.1
learn_pb: false
learned_variance: true
lgv_clip: 100.0
lgv_layers: 4
local_search: false
log_var_range: 4.0
lr_back: 0.0005
lr_flow: 0.01
lr_policy: 0.0005
lr_shrink_lambda: 0.9995
ls_cycle: 100
max_batch_size: 1000
max_iter_ls: 100
mode_bwd: tb
mode_fwd: tb
molecules_path: D:/crystal_datasets/test_qm9_dataset.pt
norm: layer
partial_energy: false
pb_scale_range: 0.1
pis_architectures: false
prioritized: boltzmann
rank_weight: 1
repeats: 10
run_name: mk_dev_runs_6_1
s_emb_dim: 32
samples_per_opt: 10
sampling: buffer
scheduler: true
seed: 12345
subtb_lambda: 2
t_emb_dim: 32
t_scale: 1.0
target_acceptance_rate: 0.574
temperature_conditioning: true
temperature_scaling_factor: 0.1
train_pb: false
use_weight_decay: false
weight_decay: 1e-7
zero_init: false
