run_name: 'mk_dev'
tag: 'dev'
seed: 12345
device: 'cuda'
cuda_memory_fraction: 0.9
anomaly_detection: False  # dramatic slowdown when True

# Checkpoints
################################################################
continue_from_checkpoint: false
continue_from_hit_prior: false
mlip_path: 'D:\crystal_datasets\esen_s.pt' # C:\Users\mikem\Downloads\acr_112025_mh1_stagetwo.model
prior_path: null
molecules_path: null
test_molecules_path: null
checkpoint_path: null

#Optimizers
################################################################
lr_policy: 5.0e-4              # learning rate of the policy network
min_lr: 1.0e-5                # ihn
lr_flow: 1.0                  # learning rate of the flow network
lr_back: 5.0e-4                # learning rate of the backward pass
lr_warmup_ratio: 25           # how much smaller the initial (warmup) LR should be than the max policy value
scheduler: True               # does LR warmup from lr/lr_warup_ratio -> lr -> min_lr over the warmup and annealing period
lr_warmup_time: 1000
lr_anneal_time: 200000
weight_decay: 1.0E-4
use_weight_decay: false
gradient_norm_clip: 0.1        # gradient norm clip for updating gfn model weights
ema_decay: 0.95 #0.99  # set to null for no ema

# model parameters
################################################################
zero_init: False
joint_layers: 4              # number of layers in forward/backward policy models
hidden_dim: 1024             # dimensionality of hidden layer
s_emb_dim: 1024               # dimensionality of state embedding
condition_emb_dim: 1024         # dimensionality of the conditioning embedding
t_emb_dim: 64                # dimensionality of time embedding
harmonics_dim: 64            # dimensionality of harmonic embedding
dropout: 0                    # dropout probability
norm: layer                   # null, "layer" - DON'T PUT 'batch'

# training params
################################################################
batch_size: 250              # number of samples per training batch
grow_batch_size: true        # whether to dynamically grow the batch size to fill the RAM
max_batch_size: 2000
batch_growth_increment: 1.01  # batch size to increment at each step - GROWS FAST!  # 1 is static, 1.1 10% growth, etc.
eval_batch_size: 1000        # batch size for evaluation (adaptive)
eval_num_samples: 1000       # minimum number of samples for evaluation
epochs: 1000000000             # number of training epochs
eval_period: 250              # how often to do evaluation & reporting
figs_period: 250             # how often to log custom figures EXPENSIVE # must be multiple of eval_period or it won't fire

# SDE integration
################################################################
eval_T: 10                  # diffusion trajectory length for inference
integrator:
  T: 10                        # static training diffusion length
  min_traj_length: 10
  max_traj_length: 10
  traj_length_strategy: static # 'static'  or 'sampled'  will do random between min and max traj lengths
  discretizer_max_ratio: 15    # maximum ratio between randomly sampled step sizes - needs to be >25 for 15 steps, or 10 for 30 steps to get good coverage at extrema
  discretizer: uniform #'random'        # 'random' 'low_discrepancy' 'equidistant' 'uniform'

t_scale: 0.05                 # scales fixed forward policy variance
log_var_range: 6           # controls dynamic range of learned policy variance, when (-1) there is no fixed range or tanh containment
pb_drift_range: 0.2          # range of learned backward drift corrections, only for 'brownian_bridge'
pb_var_range: 1             # range of learned backward policy variance
learn_pb: true               # whether to learn a correction to the backward policy in 'brownian_bridge' mode
learned_variance: True       # whether to learn policy variance

# set a constant or
# as a set of line segments [[step, value], [step, value], ...]
fwd_loss_coeffs:
  tb: 1.0
  vg_lb: 0.0
  vg_lme: 0  # exclusive with vg_lb
  emp_z: 0  # separate from tb, train Z to match the empirical lme estimate. Must combine with a VG loss
  loss_clip: 1.0E+9
bwd_loss_coeffs:
  tb: 1.0 #1.0  # will be altered by bwd_tb_z - must be nonzero for log Z backwards-trained warm start
  bwd_tb_z: 2.0 #2.0  # 2 if we should only train the Z component in tb, 1 if we should train log Z on backward TB, 0 if not. bwd tb must be >0
  vg_lb: 0
  vg_lme: 0  # exclusive with vg_lb
  emp_z: 0  # separate from tb, train Z to match the empirical lme estimate. Must combine with a VG loss
  mle: 1.0 # 1.0  # will do weighted MLE if VG is running with repeats, otherwise trajectory-wise
  loss_clip: 1.0E+9

# training style
both_ways: true             # forward and backward training
repeats: 2                   # for conditional training, multiplies batch size by this factor for VarGrad, var, buffer losses
fwd_to_bwd_ratio: 1          # whether to do forward (>1) or backward (<1) training more often - automatically set to ~0 for anchoring mode
bwd: false                   # backward training only
clipping: true  # clip the maximum step size induced by the policy model
gfn_clip: 200.0  # clip the maximum step size induced by the policy model
reward_range: null # range of reward values allowed, null to go unrestricted
# for controlling 3-phase convergence protocol # todo consolidate / cleanup
anchor_fwd_bwd: true #true  # whether to do this at all
min_fwd_bwd_ratio: 0.01
max_fwd_bwd_ratio: 1.0
thermalization_slope_err: 100.0 #0.1 #0.1
thermalization_intercept_err: 100.0 #1.0 #1.0
btb_threshold: 1.5 # DEPRECATED ratio of thermalization_conv_eps at which we activate emergency bwd training
phase_change_time: 25 #250 #1000  # time to adjust loss coefficients between phases
thermalization_conv_eps: 5.0 #0.5 # now used only for phase 2 to 3 transition
init_kld_threshold: 2.0 #0.05

# energy function settings
################################################################
energy_function: 'elj'
temperature: 2.5 # 2.5 is room temperature kT in kJ/mol
temperature_conditioning: False  # if false, temperatures are set to temperature, and there is no annealing
molecule_conditioning: False  # conditions the generative prediction on the molecule
sg_conditioning: False  # whether to conditionally sample across space groups
space_groups: [ 14 ]  # which space groups to sample over
zp_conditioning: false # whether to condition over z prime values
z_primes: [ 1 ]
# loss coefficients
energy_density_coeff: 10.0  # how much to weight the density penalty term in the energy function
bounding_coeff: 10.0
reduction_coeff: 10.0
energy_lj_coeff: 1.0  # loss coefficient