lr_policy: 0.001
lr_flow: 0.1
lr_back: 0.001
hidden_dim: 64
s_emb_dim: 64
t_emb_dim: 64
harmonics_dim: 64
batch_size: 100
epochs: 25000
buffer_size: 600000
T: 100
subtb_lambda: 2
t_scale: 1.0
log_var_range: 4.0
energy: "molecular_crystal" # "molecular_crystal"  # "many_well"
mode_fwd: "tb"
mode_bwd: "tb"
both_ways: false

# For local search
################################################################
local_search: false
# How many iterations to run local search
max_iter_ls: 200
# How many iterations to burn in before making local search
burn_in: 100
# How frequently to make local search
ls_cycle: 100
# langevin step size
ld_step: 0.1
ld_schedule: true
target_acceptance_rate: 0.574

# For replay buffer
################################################################
# high beta give steep priorization in reward prioritized replay sampling
beta: 1.0
# low rank_weighted give steep priorization in rank-based replay sampling
rank_weight: 0.01
# three kinds of replay training: random, reward prioritized, rank-based
prioritized: "rank"

bwd: false
exploratory: false
sampling: "buffer"
langevin: false
langevin_scaling_per_dimension: false
conditional_flow_model: false
learn_pb: false
pb_scale_range: 0.1
learned_variance: false
partial_energy: false
exploration_factor: 0.2
exploration_wd: true
clipping: true
lgv_clip: 100.0
gfn_clip: 10000.0
zero_init: true
pis_architectures: true
lgv_layers: 3
joint_layers: 2
seed: 12345
weight_decay: 1e-7
use_weight_decay: false
eval: false

# molecular crystal settings
temperature: 10