- index: 0
  tag: 0_just_vg
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 1
  tag: 1_vg_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 2
  tag: 2_vg_fat_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 3
  tag: 3_vg_mle_tb
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 4
  tag: 4_vg_long_mle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 5
  tag: 5_fvg_bmle
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 6
  tag: 6_just_vg_high_lr
  update_keys:
  - lr_policy
  - lr_flow
  - lr_back
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 7
  tag: 7_vg_mle_tb_clip_0.1
  update_keys:
  - beta
  - reweight_T
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 8
  tag: 8_vg_mle_tb_clip_1
  update_keys:
  - beta
  - reweight_T
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 9
  tag: 9_vg_mle_tb_clip_10
  update_keys:
  - beta
  - reweight_T
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 10
  tag: 10_vg_mle_tb_RF
  update_keys:
  - beta
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 11
  tag: 11_just_vg_RF
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 12
  tag: 12_fvg_bmle_RF
  update_keys:
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 13
  tag: 13_greedy_0_0
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 14
  tag: 14_greedy_0.01_0
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 15
  tag: 15_greedy_0.1_0
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 16
  tag: 16_greedy_0_0.01
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 17
  tag: 17_greedy_0_0.1
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 18
  tag: 18_greedy_0.01_0.01
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 19
  tag: 19_greedy_0.1_0.01
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 20
  tag: 20_greedy_0.01_0.1
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 21
  tag: 21_greedy_0.1_0.1
  update_keys:
  - exploratory
  - temperature_conditioning
  - anneal_temperature
  - space_groups
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 22
  tag: 22_vg_mle_tb_RF
  update_keys:
  - repeats
  - beta
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 23
  tag: 23_just_vg_RF
  update_keys:
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
- index: 24
  tag: 23_fvg_bmle_RF
  update_keys:
  - repeats
  - joint_layers
  - hidden_dim
  - dropout
  - norm
  - t_scale
  - pb_scale_range
  - fwd_loss_coeffs
  - bwd_loss_coeffs
  notes: ''
