defaults:
  base: base.yaml


experiments:
- tag: 0
  update:
    energy_static_temperature: 0.1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    energy_function: lj

- tag: 1
  update:
    energy_static_temperature: 0.1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    energy_function: silu

- tag: 2
  update:
    energy_static_temperature: 1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    energy_function: lj

- tag: 3
  update:
    energy_static_temperature: 1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    energy_function: silu

- tag: 4
  update:
    energy_static_temperature: 0.1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    energy_function: lj
    bwd_thermalization_time: 10000

- tag: 5
  update:
    energy_static_temperature: 0.1
    max_batch_size: 2000
    log_var_range: 4
    pb_drift_range: 0.2
    pb_var_range: 2
    energy_function: lj
    thermalization_conv_eps: 0.01
