- index: 0
  tag: 0_baseline
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 1
  tag: 1_high_cov_rat
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 2
  tag: 2_high_cov_cutoff
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 3
  tag: 3_small_model
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 4
  tag: 4_dropout
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 5
  tag: 5_big_normed
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 6
  tag: 6_5kbatch
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - max_batch_size
  notes: ''
- index: 7
  tag: 7_6layer
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
- index: 8
  tag: 8_high_varrange
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - log_var_range
  notes: ''
- index: 9
  tag: 9_flexible_pb
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - pb_drift_range
  - pb_var_range
  notes: ''
- index: 10
  tag: 10_small_base_var
  update_keys:
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  - t_scale
  notes: ''
- index: 11
  tag: 11_reinforce
  update_keys:
  - fwd_loss_coeffs
  - joint_layers
  - hidden_dim
  - s_emb_dim
  - condition_emb_dim
  - dropout
  - norm
  - prior_coverage_cutoff
  - prior_coverage_ratio
  notes: ''
